/*
This code is generated by Sasete. reach me over here, SaseteS@icloud.com
*/
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class VRCameraCollisionFix : MonoBehaviour
{

    public GameObject OVRCameraRig;
    private CameraMoveWithPlayer VRCameraCharacterControllerFix;

    private void Start()
    {
        VRCameraCharacterControllerFix = OVRCameraRig.GetComponent<CameraMoveWithPlayer>();
    }

    private void OnTriggerEnter(Collider other)
    {
        if (TriggerVRObject(other))
            VRCameraCharacterControllerFix.enabled = false;

    }

    private void OnTriggerExit(Collider other)
    {
        if (TriggerVRObject(other))
            VRCameraCharacterControllerFix.enabled = true;

    }

    private bool TriggerVRObject(Collider other)
    {
        if (other.gameObject == OVRCameraRig)
            return true;
        else
            return false;

    }

}
